### PR TITLE
PR: Add QWebEngineProfile import for PyQt5 and PySide2

### LINKED ISSUE #201: Missing QWebEngineProfile from QtWebEngineWidgets
Hello,

I'm trying substitute PySide2 with qtpy on an existing project, but apparently QWebEngineProfile is not here:

`ImportError: cannot import name 'QWebEngineProfile' from 'qtpy.QtWebEngineWidgets'` 

I guess it's all about this file: https://github.com/spyder-ide/qtpy/blob/master/qtpy/QtWebEngineWidgets.py#L20 ?

### PR DESCRIPTION
**Pull request by johndoe46**
Fixes #201

### CODE REVIEW

**Comment by dalthviz** [comment]
Closing (and reopening) to check if a proper CI run is triggered

**Comment by dalthviz** [comment]
Since the repository with the changes was deleted is not possible to reopen.

@johndoe46 would you like to send us another PR with the changes you proposed here? Let us know!

**Comment by ccordoba12** [comment]
@dalthviz, please don't forget a PR to merge this one.

**Comment by johndoe46** [comment]
> Since the repository with the changes was deleted is not possible to reopen.
> 
> @johndoe46 would you like to send us another PR with the changes you proposed here? Let us know!

That was two (!) years ago. Since then there's Pyside6 and this PR is now obsolete. I will not submit another PR as I have no interest in qtpy now (directly using Pyside6). Thanks for the heads-up anyway.

**Pull request closed without merging**
