### PR TITLE
PR: Fix `LibraryLocation` -> `LibraryPath` renaming due to deprecation with Qt6

### PR DESCRIPTION
**Pull request by StSav012**
That was a minor omission.

### CODE REVIEW

**Comment by StSav012** [comment]
More info on the change: https://doc.qt.io/qt-6/qlibraryinfo-obsolete.html

**Review by dalthviz — COMMENTED** [review]
Hi @StSav012 thank you for the help with this! I think we should add a test for this. It should go inside [`test_qtcore.py`](https://github.com/spyder-ide/qtpy/blob/master/qtpy/tests/test_qtcore.py) and be something similar to the tests we have for `QLibraryInfo.location`: https://github.com/spyder-ide/qtpy/blob/371ec52e6b687ae89b3e422ff2a13cba28d4bd85/qtpy/tests/test_qtcore.py#L65-L68

Other than that, this LGTM :+1: If you have any question to implement the test let us know!

**Comment by StSav012** [comment]
Hi @dalthviz,

Thank you for the feedback. Forgive me for not looking through the tests, for I'm not disciplines enough (yet) to make tests for my code.

As a side note, is line https://github.com/spyder-ide/qtpy/blob/371ec52e6b687ae89b3e422ff2a13cba28d4bd85/qtpy/tests/test_qtcore.py#L73 in the tests correct? I would expect an `assert` there, like you have in similar places. On the other hand, if there is no `exec_` function, the expression should raise an `AttributeError`, right? Then, many `assert`s aren't necessary at all.

**Comment by dalthviz** [comment]
> in the tests correct? I would expect an assert there, like you have in similar places. On the other hand, if there is no exec_ function, the expression should raise an AttributeError, right? Then, many asserts aren't necessary at all.

You are probably right there @StSav012 ! In general I believe we have a lot of room for improvement regarding testing 😅 If you want to help with that or have any ideas feel free to open a new issue to discuss and maybe plan what changes we could do to improve our test suite :)

**Review by dalthviz — APPROVED** [review]
Thanks @StSav012 !

**Pull request merged**
