### PR TITLE
PR: Handle C style header for custom widget

### PR DESCRIPTION
**Pull request by diorcety**
Convert c style header in python import (like pyside-uic)

### CODE REVIEW

**Comment by ccordoba12** [comment]
@diorcety, thanks for your contribution!

Could you better explain the rationale behind this change please?

**Comment by diorcety** [comment]
By default pyside-uic convert C header field for custom widget in python import.
Cf https://github.com/pyside/Tools/blob/master/pysideuic/uiparser.py#L807

**Comment by ccordoba12** [comment]
@diorcety, thanks for the explanation.

@astrofrog, do you approve this one?

**Comment by astrofrog** [comment]
Is there an easy way to add a test for this?

**Comment by ccordoba12** [comment]
@diorcety, please do find a way to add a test for this.

**Comment by diorcety** [comment]
ok I wil try

**Comment by ccordoba12** [comment]
@diorcety, thanks a lot for the test! Things look really good to me now.

@astrofrog, do you approve?

**Comment by ccordoba12** [comment]
Pinging @astrofrog again. @astrofrog, I'd like to release 1.3 this week, so if you don't answer, we'll leave this for 1.4.

**Comment by astrofrog** [comment]
Is the ``qcombobox_subclass.h`` file missing from here? If so, why does this not error?

**Comment by diorcety** [comment]
The goal of this support is take a UI from a C++ project and use it in python project by changing h files by python file. qcombobox_subclass.h doesn't exist but qcombobox_subclass.py do.

**Pull request closed without merging**
