### PR TITLE
PR: Update RELEASE.md for 1.x version

### PR DESCRIPTION
**Pull request by dalthviz**
Update `RELEASE.md` following current branch structure (`master` and `1.x`) and add some missing info

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Per discussion with @dalthviz and myself, given there are some important additions here that would be very useful in `master` as well, and I like the formatting and structure a lot better than what I originally did, I'm going to integrate the `master` changes in here and fix a few typos/grammar issues, so we can then non-null merge all these improvements to master with just a find-replace of `1.x` to `master` and tweaking the package build line. Marking it as draft until that's done...

**Review by CAM-Gerlach — APPROVED** [review]
Thanks @dalthviz for the great improvements! LGTM now that I synced the additions and improvements with those in `master`, minus a few `master`-specific things. @ccordoba12 and @dalthviz , would you mind reviewing? Once this is ready, I can take care of the merge, as there are a few things (a couple more than I initially thought) that I'll need to take care of when merging to `master`. Thanks!

**Review by dalthviz — COMMENTED** [review]
Thanks @CAM-Gerlach for the changes! LGTM :+1:

**Review by ccordoba12 — COMMENTED** [review]
Looks good to me, thanks @dalthviz and @CAM-Gerlach!

**Comment by dalthviz** [comment]
You will take care of the merge with master right @CAM-Gerlach ?

**Comment by CAM-Gerlach** [comment]
Yup, in work now

**Comment by dalthviz** [comment]
Just in case @CAM-Gerlach I merged https://github.com/spyder-ide/qtpy/pull/278  (maybe that can affect the merge you started doing 😅 )

**Comment by CAM-Gerlach** [comment]
Yeah, you could say it "affected" it...if by "affected" you mean blocked me when I tried to push and forced me to start over since it created new commits on upstream between the time I started the merge and when I finished :laughing: 

It wasn't _that_ bad, I did some juGitsu and managed to not have to do _everything_ over, just the Git parts haha, just FYI next time let's maybe not merge something to master at the same time, hmm? :wink:

**Comment by CAM-Gerlach** [comment]
In all seriousness, it took me longer to write that than actually fix the problem jaja, no worries

**Comment by CAM-Gerlach** [comment]
Also, separately merged the release per the new release guide

**Pull request merged**
