### PR TITLE
PR: Add QtWinExtras module

### PR DESCRIPTION
**Pull request by phil65**

### CODE REVIEW

**Review by jschueller — APPROVED** [review]

**Comment by jschueller** [comment]
ping @goanpeca

**Comment by dalthviz** [comment]
Closing (and reopening) to trigger CI run

**Comment by dalthviz** [comment]
Hi @phil65 thank you for your contribution! Seems like `QtWinExtras` is not available on conda with Python 3 and on pip it doesn't have some modules or maybe the access is different (like `QtWinExtras.QtWin`) Could you do a check and do the validations for the test to pass? Let us know!

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks for your contribution @phil65!

**Pull request merged**
