### PR TITLE
Install Pyside2 from conda-forge

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by ccordoba12** [comment]
I don't agree with this because it implies some regressions in our tests. Perhaps we should move the official Qt packages to another location that doesn't have download issues.

**Comment by ccordoba12** [comment]
> What regressions are you talking about ?

Sorry, there are not regressions, but I saw you're commenting tests that are passing right now.

**Comment by ccordoba12** [comment]
So I think it's better to download the official Qt PySide2 wheels and put them in Bintray or something, the change the URL here, and that'll solve the failures in CIrcleCI.

**Comment by dpizetta** [comment]
I think this problem with pyside2 servers are solved... https://bugreports.qt.io/browse/PYSIDE-684 :)

**Comment by jschueller** [comment]
cool

**Pull request closed without merging**
