### PR TITLE
PR: Add wrapper around sip/shiboken isdeleted/isvalid (compat.py)

### LINKED ISSUE #302: Compat shiboken and sip like Qt.py
Qt.py compat with shiboken and sip modules

```python
from Qt.compat import wrapInstance,isValid
```

This is very helpful in some case.

### PR DESCRIPTION
**Pull request by zjp**
Fixes #302 

This just adds a wrapper around the sip.isdeleted and shiboken.isValid functions

### CODE REVIEW

**Review by dalthviz — COMMENTED** [review]
Thanks @zjp for helping with this! Could it be possible to add some sort of test for this new function (in something like `qtpy/tests/test_compat.py`)?

Other than this LGTM :+1:

**Comment by zjp** [comment]
Yes, absolutely! I'll force-push some tests when I think of a good one.

**Comment by zjp** [comment]
OK, I've added what I hope is a satisfactory test.

**Comment by zjp** [comment]
Aha, if you're going quick it's easy to overlook isdeleted and isValid are semantically opposites... that should fix it.

**Review by dalthviz — APPROVED** [review]
Thanks @zjp for your work on this! LGTM :+1:

**Comment by zjp** [comment]
No problem, I'm happy to contribute!

**Pull request merged**
