### PR TITLE
Move QStringListModel to QtCore

### PR DESCRIPTION
**Pull request by almarklein**
Supersedes #72

### CODE REVIEW

**Comment by almarklein** [comment]
Is the failing CI a glitch?

**Comment by ccordoba12** [comment]
I think there are some conflicts between the latest Qt Continuum build on Mac and PySide (which is a very old package).

I'll take a look at this next week :-)

**Comment by almarklein** [comment]
👍  I am not in a hurry. I am vendoring qtpy (at least for now).

**Comment by ccordoba12** [comment]
Thanks @almarklein and sorry for the big delay on this one. If you need any more things for Pyzo, please submit your PRs this week because I'm about to release qtpy 1.2 :-)

**Pull request merged**
