### PR TITLE
PR: Add QtPdf

### LINKED ISSUE #381: Add QtPdf, QtPdfWidgets
these are new in 6.x

### PR DESCRIPTION
**Pull request by jschueller**
Closes #381

### CODE REVIEW

**Review by dalthviz — COMMENTED** [review]
Thanks @jschueller for helping with this! Checking, I think that the `QtPdf` and `QtPdfWidgets` modules are only available in PyQt6 and PySide6 >=6.4.0. Taking that into account, maybe we should put in place a try-catch for the PyQt6 and PySide6 import calls and raise a `QtBindingMissingModuleError` in case of an `ImportError`? What do you think?

Beside that, could you rebase on top of the latest master, please? That should fix the failing test.

Other than the above this LGTM :+1:

**Comment by jschueller** [comment]
ok, I rebased
I think ImportError is fine, what does QtBindingMissingModuleError bring to the table ?

**Comment by dalthviz** [comment]
Thanks for the quick response! And regarding raising `QtBindingMissingModuleError` is just to be consistent with other imports that use the specific error classes that QtPy implements and also to show that is expected for the module import to fail in some circumstances (in this case if PyQt6 or PySide6 >=6.4)

**Comment by jschueller** [comment]
thtat's not what is done for other modules, let's keep it simple

**Review by dalthviz — APPROVED** [review]
Thanks again @jschueller for your help with this! Thinking a little bit more, there is no need to hold this for being merged. Indeed, keeping things simple is better, and actually there is no qtpy error implemented that encapsulates the case of a module not being available in a specific binding version (maybe in the future we could add it but for the moment the `ModuleNotFoundError` should be fine 👍🏼 )

**Pull request merged**
