### PR TITLE
PR: If a Qt binding is already imported, then use it.

### LINKED ISSUE #138: If one binding has already been imported, then qtpy should just use it
Consider, for example, a system where solely pyqt4 and pyqt5 are installed.  If one does
```
import PyQt5.QtGui
import qtpy
```
this fails with
```
qtpy.PythonQtError: No Qt bindings could be found
```
(even though obviously there is a Qt binding available) because PyQt4.QtGui cannot be imported at all after PyQt5.QtGui has already been imported.

Fortunately there is an easy solution, which is to check, before doing anything else, whether PyQt4/5/PySide/2 are already present in sys.modules, and, if one of them is, just use it.

Real use case:
matplotlib (which can use any of the bindings) is considering switching from using its own qt shim to qtpy.  However, it is not rare that one user specifies a given binding to use (via the matplotlibrc backend param), but sometimes wants to use some GUI program that is explicitly written (solely) against PyQt5.  Then starting the GUI will import PyQt5 and matplotlib would fail to initialize its backend if it did not first check whether a given binding had already been forced for the process.

### PR DESCRIPTION
**Pull request by anntzer**
Fixes #138.

See #138 for rationale.

### CODE REVIEW

**Comment by goanpeca** [comment]
Looks good, some test failing though. Any chance we could write a test for this?

**Comment by anntzer** [comment]
Properly testing this looks slightly tricky as it appears that currently you have four CI setups each with just one of the dependencies installed, but to test this feature meaningfully you'd need another setup with two of them installed.

We've been seeing failing tests (segfaulting) with the recently released pyqt5.10 on matplotlib as well and have downgraded the CI to use pyqt5.9.  Do you know whether qtpy master passes with pyqt5.10?

**Comment by ccordoba12** [comment]
> Properly testing this looks slightly tricky

I agree. Since this change is quite minimal and easy to understand, I'm ok to not add a test for this one. Besides, Matplotlib is going to be the real test for this addition.

 @goanpeca?

> We've been seeing failing tests (segfaulting) with the recently released pyqt5.10 on matplotlib as well and have downgraded the CI to use pyqt5.9

Ok, good to know. Let me pin pyqt to 5.9 here too, so our tests can pass @anntzer.

**Comment by ccordoba12** [comment]
@anntzer, please rebase against master to get the fix for our tests.

**Comment by anntzer** [comment]
done

**Comment by ccordoba12** [comment]
Thanks @anntzer for this. Being a dependency of Matplotlib is a huge achievement for a small project like this one!

I'll try to release 1.4 as soon as possible (a couple of weeks at most).

**Comment by anntzer** [comment]
It's not a dependency yet but may become one soon... (https://github.com/matplotlib/matplotlib/issues/6118)

**Comment by ccordoba12** [comment]
Yep, I know.

**Comment by ccordoba12** [comment]
@anntzer, qtpy 1.4 is out!

**Comment by anntzer** [comment]
thanks for the note :)

**Pull request merged**
