### PR TITLE
PR: Move CI to Github Actions

### PR DESCRIPTION
**Pull request by goanpeca**
@ccordoba12 I added as much options as possible with github actions. 

Which versions should we test for python and which builds could we skip?

It is still pretty fast with the current setup.

### CODE REVIEW

**Comment by ccordoba12** [comment]
> Which versions should we test for python and which builds could we skip?

I think Python 2.7, 3.7 and 3.8 should be fine.

**Comment by goanpeca** [comment]
@ccordoba12 I suggest we use the oldest version we support and the newest, since older version are more likely to produce "issues", in that case, would that be

2.7 3.6 and 3.8?

**Comment by CAM-Gerlach** [comment]
Given the other CIs no longer run at all, (perhaps they were disabled site-level?) unless we re-enable them we need to finish and merge this before merging anything else, to avoid committing untested code. I'm going to try to get this working again.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Any insight on why the CIs were disabled? It seems this project has gone essentially unmaintained for the past year, despite substantial community interest and it being in the top 200 packages on PyPI... I'll do my best to put out some fires where I can.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I had to fix a number of outstanding and accumulated issues with it, update it to the latest versions of the relevant deps and fix some sub-optimal practices, rebase and clean up the commit history, update the relevant metadata and make some other improvements, but this should be all good to merge now.Most notably, because the Qt4 packages appear to no longer be available on either pip or conda for any supported platform or channel, I had to drop those tests, though otherwise support for Qt4 itself is not officially dropped anywhere other than the CI tests. However, we should consider perhaps cutting a 1.10 release with these changes, updated metadata and the other pending PRs, and then a 2.0 release with support for Qt4 and Python 2.7 dropped (since we are no longer able to test that platform, and Python 2.7 has been EoL for over a year).

**Review by CAM-Gerlach — APPROVED** [review]
With my plethora of fixes, LGTM now.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 gave the okay to go ahead with this, so I'll merge this now to get our CIs working and unblock the other PRs

**Pull request merged**
