### PR TITLE
PR: Update README sponsors section

### PR DESCRIPTION
**Pull request by dalthviz**

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Hey @dalthviz , was this intended to be a draft PR? Looks like the inline image isn't rendering; otherwise, everything LGTM so far :+1:

**Review by ccordoba12 — COMMENTED** [review]
Please add the Numfocus logo next to the Quansight one (as we do in our other repos).

Also, is there a Quasight logo with a transparent background we could use? I think it'd be nicer than having one with white background.

**Review by CAM-Gerlach — APPROVED** [review]
LGTM, thanks @dalthviz !

**Review by ccordoba12 — APPROVED** [review]
Looks good to me now, thanks @dalthviz!

**Pull request merged**
