### PR TITLE
Use the right PyQt4/PySide QtGui classes in QtWidgets and QtGui

### PR DESCRIPTION
**Pull request by ccordoba12**
Instead of importing all of `{PyQt4, Pyside}.QtGui` in those modules, now we import exactly what's needed to maintain compatibility with PyQt5.

### CODE REVIEW

**Comment by ccordoba12** [comment]
I can rebase this after #9 is merged :-)

**Comment by goanpeca** [comment]
Really good!, this will avoid using the wrong way in PyQt4

LGTM :+1:

**Comment by ccordoba12** [comment]
Yep, that was the idea! ;-)

**Comment by ccordoba12** [comment]
@goanpeca, I'll start Spyder migration to qtpy this weekend. Please hold the a new release until I finish the migration, in case I find some missing things :-)

**Comment by goanpeca** [comment]
Got it

**Comment by ccordoba12** [comment]
Sorry, we do need a new release so that Travis and AppVeyor work (forgot about that).

Could you tag and release 1.0 to PyPi and our anaconda channel, please?

**Comment by goanpeca** [comment]
1.0.0b1 ?

1.0.0rc1  ?

**Comment by ccordoba12** [comment]
1.0b1 is fine. I don't think we're going to need three number for qtpy 
here. Bugfix releases can be 1.1, 1.2, etc.

**Pull request merged**
