### PR TITLE
Fix "Prefer `format()` over string interpolation operator" issue

### PR DESCRIPTION
**Pull request by goanpeca**
This pull request automatically fixes all occurrences of the following issue:

Issue type: [Prefer `format()` over string interpolation operator](https://www.quantifiedcode.com/app/issue_class/4ACGxFj1)
Issue details: [https://www.quantifiedcode.com/app/project/gh:spyder-ide:qtpy?groups=code_patterns/%3A4ACGxFj1](https://www.quantifiedcode.com/app/project/gh:spyder-ide:qtpy?groups=code_patterns/%3A4ACGxFj1)

To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.

Legal note: We won't claim any copyrights on the code changes.

Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)

### CODE REVIEW

**Comment by goanpeca** [comment]
@spyder-ide/core-developers testing a new tool called quantified code.

Its pretty cool :-)

**Comment by Nodd** [comment]
The tool looks cool, but I'd reject this pull request because:
1. String interpolation is not bad for small string like these
2. It's not what a human would write, the tool was careful to keep the exact same functionality but in both cases `{0}` is enough.

**Comment by ccordoba12** [comment]
I agree with @Nodd: using  `{0}` is enough in both cases.

**Comment by ccordoba12** [comment]
I did the changes myself to be able to release 1.0.2 (which I need to better support QtWebEngine in 5.6 :-)

**Pull request merged**
