### PR TITLE
Add improvements and missing imports from Spyder Qt shim

### LINKED ISSUE #5: Add PYQT5 / PYQT4/PYSIDE boolean variables
Spyder has a number of global variables for convenience to check whether we are running on PyQt5, PyQt4 or PySide.
It would be nice if those were moved to qtpy. I think that anyone using qtpy could use those.

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #5

----

Spyder is much more battle tested than qtpy or pyqode, so I prefer to use as much as we can from its shim here.

### CODE REVIEW

**Comment by ccordoba12** [comment]
The main difference now is that `QT_API` has to be in lower caswe, but that's the custom elsewhere.

**Comment by ccordoba12** [comment]
Another important thing is that I replaced most of the current `qtpy/__init__.py` with `spyderlib/qt/__init__.py` because the first one was not working and second is much more stable.

**Comment by ccordoba12** [comment]
Finally, given the importance of this change, I think we should bump `qtpy` version to **0.2.0**

**Comment by ccordoba12** [comment]
I'd even say that we should bump `qtpy` version to **1.0** because after these changes and those in #10 it should be pretty stable :-)

**Comment by ccordoba12** [comment]
Of course, my main interest with all this is to start using `qtpy` in Spyder itself since beta3 ;-)

**Comment by goanpeca** [comment]
LGTM :+1:

**Pull request merged**
