### PR TITLE
Some improvements to our tests in Travis

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by goanpeca** [comment]
Nope, you need to spell the whole matrix by system otherwise, hyou just removed those tests from Mac as well

**Comment by goanpeca** [comment]
```yaml

language: python
...
matrix:
  include:
    # Linux
    - os: linux
      python: "2.7"
      env: USE_QT_API=PyQt4
    - os: linux
      python: "3.4"
      env: USE_QT_API=PyQt4

ETC...
```

**Comment by ccordoba12** [comment]
Yes, I just noticed, my mistake :-)

**Comment by ccordoba12** [comment]
It seems `.travis.yml` still has errors. Given that I don't have time for this, and this is a simple change but adds a lot of complexity to that file, I'm closing this one :-)

**Comment by goanpeca** [comment]
Will fix it later on

**Pull request closed without merging**
