### PR TITLE
PR: Add QtQuickWidgets

### PR DESCRIPTION
**Pull request by KurtJacobson**
This PR adds support for QtQuickWidgets.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Please skip

    qtpy/tests/test_patch_qcombobox.py::test_model_item

in Pyside2 to see if our tests pass there.

**Comment by ccordoba12** [comment]
@KurtJacobson, please remove your last commit. I'm going to fix the failures with our tests in PR #180.

**Comment by KurtJacobson** [comment]
@ccordoba12 Excellent! I will revert 104b33c.

**Comment by ccordoba12** [comment]
@KurtJacobson, please rebase or merge with latest master to get the fixes.

**Comment by ccordoba12** [comment]
Also, a test is missing for your change.

**Comment by KurtJacobson** [comment]
@ccordoba12 Will do, and I'll add the tests. Thank you!

**Comment by ccordoba12** [comment]
1.6.0 is out, with this change. Enjoy!

**Comment by KurtJacobson** [comment]
@ccordoba12 Thanks for the very quick release!

**Pull request merged**
