### PR TITLE
PR: Use relative imports so its vendored more easily

### PR DESCRIPTION
**Pull request by almarklein**
I only need QtCore, QtGui, QtWidgets, so it would be nice if I can vendor-in part of the qtpy project. Having relative imports makes this much easier.

### CODE REVIEW

**Comment by goanpeca** [comment]
@ccordoba12 or @Nodd any comments?

**Comment by Nodd** [comment]
Very good idea! And good ideas are even better with a PR :)

**Comment by ccordoba12** [comment]
I agree with @Nodd. @Nodd, could you review @almarklein's work and merge it? I'm a bit busy right now :-)

**Comment by Nodd** [comment]
Done ! Thanks !

**Pull request merged**
