### PR TITLE
PR: Add workaround for `mode` argument in QTextCursor.movePosition (Pyside2)

### PR DESCRIPTION
**Pull request by rear1019**
See commit message/comment in code for details.

### CODE REVIEW

**Review by dalthviz — APPROVED** [review]
Thanks @rear1019 for helping with this! LGTM :+1:

Also, maybe could be worthy to open an issue over PySide @ccordoba12 @rear1019 ? The only one I found related to this is closed: https://bugreports.qt.io/browse/PYSIDE-185

**Comment by CAM-Gerlach** [comment]
> Also, maybe could be worthy to open an issue over PySide @ccordoba12 @rear1019 ? The only one I found related to this is closed: https://bugreports.qt.io/browse/PYSIDE-185

I'm not sure they're still accepting bug reports against PySide2 since they've stopped providing LTS for open source users, but it could potentially be patched in the PySide2 conda packages.

**Comment by rear1019** [comment]
PySide6 is affected as well. At the very least, one gets an exception as with PySide2 >= 5.15.3

**Comment by ccordoba12** [comment]
Please open a pull request to patch Pyside6 as well.

**Pull request merged**
